---
# --- Global Management Credentials (AVD 6.x Format) ---
aaa_settings:
  local_users:
    - name: admin
      privilege: 15
      role: network-admin
      sha512_password: "$6$l6B...your_hash..." # Encrypt this with ansible-vault later

# --- Global Layer 2 & AVD Design Settings ---
# These are "Design" variables that AVD 6.x understands directly
spanning_tree_mode: mstp
spanning_tree_priority: 32768


# --- Custom Configuration Section ---
# This section is for settings that the "Design" engine doesn't own directly.
# Moving SNMP and AAA Server Groups here stops the [WARNING] messages.
custom_structured_configuration:
  snmp_server:
    contact: "Global Network Operations Center <gnoc@example.com>"
    location: "Global Campus Fabric"
    communities:
      - name: ro-community-string
        access: ro
      - name: rw-community-string
        access: rw

  aaa_server_groups:
    - name: TACACS_GROUP
      type: tacacs+
      nodes:
        - server: 10.10.1.50
        - server: 10.10.1.51
