---
# Regional Management Settings for APAC
timezone: Asia/Singapore

# NTP Settings (Regional)
ntp_settings:
  servers:
    - name: 10.30.1.10
      prefer: true
    - name: 10.30.1.11

# DNS Settings (Regional)
name_server:
  nodes:
    - 10.30.1.5
    - 10.30.1.6

# AAA Settings (Regional TACACS+)
aaa_server_groups:
  - name: TACACS_GROUP
    type: tacacs+
    nodes:
      - server: 10.30.1.50
      - server: 10.30.1.51

# CloudVision (CVP) Settings
cv_settings:
  - 10.30.1.20
cvp_ingest_primary_allowed_vrfs:
  - MGMT
