---
# Regional Management Settings for NALA
timezone: America/Los_Angeles

# NTP Settings (Regional)
ntp_settings:
  servers:
    - name: 10.20.1.10
      preferred: true
    - name: 10.20.1.11

# DNS Settings (Regional)
name_server:
  nodes:
    - 10.20.1.5
    - 10.20.1.6

# AAA Settings (Regional TACACS+)
aaa_server_groups:
  - name: TACACS_GROUP
    type: tacacs+
    nodes:
      - server: 10.20.1.50
      - server: 10.20.1.51

# CloudVision (CVP) Settings
cvp_instance_ips:
  - 10.20.1.20
cvp_ingest_primary_allowed_vrfs:
  - MGMT
