---
# Global fabric configuration variables
root_dir: '{{ inventory_dir}}/..'

fabric_name: GLOBAL # it has to match the inventory group as mentioned here: https://avd.arista.com/devel/ansible_collections/arista/avd/roles/eos_designs/docs/data-models.html?h=fabric_name#fabric-topology-hierarchy

fabric_numbering:
  node_id:
    algorithm: "pool_manager"

management_eapi:
  enabled: true
  enable_https: true

default_node_types:
  - node_type: spine
    match_hostnames:
      - ".*SPINE.*"
  - node_type: l3leaf
    match_hostnames:
      - ".*LEAF.*"
