---

custom_structured_configuration_snmp_server:
  contact: "Global Network Operations Center <gnoc@example.com>"
  location: "Global Campus Fabric"
  communities:
    - name: ro-community-string
      access: ro
    - name: rw-community-string
      access: rw
