---
fabric_name: LAB

# FLAT VARIABLES (Highest safety against overwriting)
loopback_ipv4_pool: 10.255.0.0/24
vtep_loopback_ipv4_pool: 10.255.1.0/24
p2p_uplinks_ipv4_pool: 10.255.2.0/24

node_type_keys:
  - key: spine
    type: spine
  - key: l3leaf
    type: l3leaf

bgp_as: 65000

tenants:
  - name: LAB_TENANT
    mac_vrf_vni_base: 10000
    vrfs:
      - name: TEST_VRF
        vrf_id: 1
        svis:
          - id: 10
            name: Lab_Test_VLAN
            enabled: true
            ip_virtual_router_addresses:
              - 10.0.0.1
          - id: 20
            name: Access_Points
            enabled: true
            ip_virtual_router_addresses:
              - 10.0.1.1
            # AVD 6.0 syntax for node-specific SVIs
            nodes:
              - node: LABRLEAF01A
              - node: LABRLEAF02A
              - node: LABRLEAF03A
